[package]
name = "tictactoe-async"
version = "0.1.0"
authors = ["Tristan Phease"]
edition = "2018"
license = "MIT"

[dependencies]
async-tungstenite = "0.13.1"
serde = "1.0"
serde_json = "1.0"
futures = "0.3"
async-std = "1.9.0"
fastrand = "1.4.1"
common = {path = "../common"}