[package]
name = "common"
version = "0.1.0"
authors = ["Tristan Phease"]
edition = "2018"
license = "MIT"

[dependencies]
fastrand = "1.4.1"
serde_json = "1.0.64"
serde = { version = "1.0.125", features = ["derive"] }